apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sputnik
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvsputnik
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sputnik-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: FPSAK_BASE_URL
      value: http://fpsak.teamforeldrepenger.svc.nais.local
    - name: STS_BASE_URL
      value: http://security-token-service.default.svc.nais.local
